name: Update Recent Activity
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # must be under env:
        with:
          GH_USERNAME: "lakshit2234"                  # your GitHub username
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 5
